title: Bình Yên Trong Gió
email: ""
description: >-
  Góc đọc truyện nhẹ nhàng của Mellifluous.
baseurl: /binhyentronggio
url: ""
lang: vi
markdown: kramdown
permalink: pretty
collections:
  stories:
    output: true
  chapters:
    output: true
defaults:
  - scope:
      path: ""
      type: stories
    values:
      layout: story
  - scope:
      path: ""
      type: chapters
    values:
      layout: chapter
exclude:
  - node_modules
  - package.json
  - package-lock.json
